### ISSUE TITLE
Allow resources other than FileSystemResource

### ISSUE THREAD

**Issue by AlexanderDahmen** [V1ncNet/spring-boot-dkim-javamail#1]
Hello,

I wanted to use this library to sign outgoing messages with DKIM.  
This library is a great help with that, so thank you for providing it!

That being said, I have one issue I'd like to address.
Currently, the DER signing key is configured by `dkim.private-key`, which is of type `String` and used to reference a `FileSystemResource` location in Spring Framework.
```java
    DkimSigner dkimSigner(DkimProperties properties) throws IOException, InvalidKeySpecException, NoSuchAlgorithmException {
        Resource resource = new FileSystemResource(properties.getPrivateKey());
```

A better solution would be to change the type of `DkimProperties.privateKey` to `Resource`, which would allow Spring to directly use the default `ResourceLoader` to load different types of resources.
In my case, I'd like the private key to be in the JAR resources and addressed as `classpath:dkim/private.der`.
This is currently not possible with the resource being hardcoded as a FileSystemResource.

Thank you and have a nice day,
Alexander Dahmen

**Comment by AlexanderDahmen** [comment]
As a workaround, I am currently using a custom `@Configuration` class for setting up the `DkimJavaMailSender` bean and disabling the `DkimSignerAutoConfiguration`.

**Comment by V1ncNet** [comment]
Hi Alexander,

thanks for your suggestion. I'm on it and will release version 1.2.0 later this day. The protocols file: and classpath: and probably others as well as the legacy way will be supported.

**Comment by AlexanderDahmen** [comment]
That's great, thank you!
Another issue I found after writing this was that not all methods for sending MIME-Messages are overridden correctly.
I've had to make an anonymous subclass to use the `send(MimeMessage messages)` method with DKIM signature:

```java
        DkimJavaMailSender sender = new DkimJavaMailSender(signer) {
            @Override
            public void send(MimeMessage mimeMessage) throws MailException {
                super.send(createSignedMimeMessage(mimeMessage));
            }
        };
```

**Comment by AlexanderDahmen** [comment]
I also looked through your commit referencing this issue, and I have a note:
You instantiate a new `DefaultResourceLoader` in `DkimSignerAutoConfiguration.java`, line 48.
This works for most cases, but not if someone's SpringBoot configuration autowires a custom ResourceLoader implementation.

Instead of using a `String` to configure the private-key in `DkimProperties`, you can use type `Resource` to automatically wire up the correct resource from within Spring's ConfigurationProperties system.
In some IDEs, like IntelliJ, this will also offer Autocomplete for available resources when editing the `application.properties` file.

**Comment by V1ncNet** [comment]
> I also looked through your commit referencing this issue, and I have a note:
> You instantiate a new `DefaultResourceLoader` in `DkimSignerAutoConfiguration.java`, line 48.
> This works for most cases, but not if someone's SpringBoot configuration autowires a custom ResourceLoader implementation.

This shouldn't be a problem IMO as the project doesn't rely on any autowired ResourceLoader.

> Instead of using a `String` to configure the private-key in `DkimProperties`, you can use type `Resource` to automatically wire up the correct resource from within Spring's ConfigurationProperties system.
> In some IDEs, like IntelliJ, this will also offer Autocomplete for available resources when editing the `application.properties` file.

I totally know what you mean, but change is severe and would break the API which results in incrementing the major version number. I would rather open a new issue and postpone this change.

**Comment by V1ncNet** [comment]
I didn't mean to sound rude, but ... am I missing something here? Do you have an example?

**Comment by AlexanderDahmen** [comment]
> I didn't mean to sound rude, but ... am I missing something here? Do you have an example?

No problem

What I mean is that you can simply type your configuration property like this:
```java
@ConfigurationProperties(prefix = "dkim")
public class DkimProperties {

    private String signingDomain;
    private String selector;
    private Resource privateKey; // <-- Using Resource as config value type
    // .....
```

When doing this, the SpringBoot configuration automatically loads the correct resource using the globally configured ResourceLoader.
You can then use the resource in your AutoConfiguration like this:
```java
    @Bean
    @Conditional(PrivateKeyNotEmpty.class)
    @ConditionalOnMissingBean
    DkimSigner dkimSigner(DkimProperties properties) throws IOException, InvalidKeySpecException, NoSuchAlgorithmException {
        // Before:
        //Resource resource = new FileSystemResource(properties.getPrivateKey());

        // After:
        Resource resource = properties.getPrivateKey();

        DkimSigner signer = new DkimSigner(properties.getSigningDomain(), properties.getSelector(), resource.getInputStream());
        // .....
```

**Comment by V1ncNet** [comment]
That's pretty helpful, thanks. I got a solution to use the Resource class and maintain the legacy approach.

**Comment by AlexanderDahmen** [comment]
Nice work, well done!
Thank you for addressing and implementing this quickly, I'll update the library and usage as soon as it's available
